// Fallback seed data module for Vercel serverless deployment
// This module provides in-memory data matching Prisma query result shapes
// so the app works without a database.

const NOW = Date.now()
const DAY = 24 * 60 * 60 * 1000

function iso(daysOffset: number = 0): string {
  return new Date(NOW + daysOffset * DAY).toISOString()
}

// Deterministic CUID-like IDs (stable across calls)
function cuid(seed: number): string {
  const chars = 'abcdefghijklmnopqrstuvwxyz0123456789'
  let id = ''
  for (let i = 0; i < 25; i++) {
    id += chars[(seed * 31 + i * 17) % chars.length]
  }
  return id
}

// ====== LEAD DATA (50 leads) ======

interface LeadRecord {
  id: string
  name: string
  sector: string
  subSector: string
  location: string
  area: string
  phone: string
  rating: number
  tier: number
  stage: string
  status: string
  source: string
  notes: string
  address: string
  hours: string
  services: string
  onlinePresence: string
  recommendedPackage: string
  estimatedValue: number
  hasWebsite: boolean
  lastContact: string | null
  nextAction: string
  nextActionDate: string | null
  hotLead: boolean
  createdAt: string
  updatedAt: string
  activities?: ActivityRecord[]
}

interface ActivityRecord {
  id: string
  leadId: string
  type: string
  summary: string
  outcome: string
  date: string
  lead?: { id: string; name: string }
  createdAt: string
}

interface CampaignRecord {
  id: string
  name: string
  type: string
  status: string
  targetSector: string
  message: string
  emailsSent: number
  openRate: number
  responseRate: number
  createdAt: string
  updatedAt: string
}

// ====== DENTAL LEADS (1-21) ======

const dentalLeadsRaw = [
  {
    name: "Dr. Elaine de Lange Dentist",
    sector: "Dental",
    subSector: "General & Cosmetic Dentistry",
    location: "Hatfield, Pretoria",
    area: "Hatfield",
    phone: "+27 67 163 8738",
    rating: 4.9,
    tier: 1,
    stage: "new",
    status: "active",
    source: "research",
    notes: "SINGLE HIGHEST-PRIORITY LEAD. Glowing reviews for root canal work and pregnancy care. Built audience, zero digital home. Conversion-ready prospect. Facebook (562 likes, 9 check-ins), Medpages, Old Mutual, Polomap.",
    address: "Hatfield Wellness Centre, 454 Hilda St, Hatfield, 0028",
    hours: "Mon/Wed: 8AM-4PM | Tue/Thu/Fri: 8AM-1PM",
    services: "General Dentistry, Cosmetic, Dental Hygiene, Pediatric",
    onlinePresence: "Facebook (562 likes), Medpages, Old Mutual, Polomap",
    recommendedPackage: "Crown (R8,999)",
    estimatedValue: 8999,
    hasWebsite: false,
    hotLead: true,
    nextAction: "Build ProtoLead demo site, then call receptionist",
    nextActionDateDays: 2,
  },
  {
    name: "The Dental Doc (Dr Mythili Swaminathan)",
    sector: "Dental",
    subSector: "General Dentistry",
    location: "Centurion",
    area: "Eldoraigne",
    phone: "+27 12 658 3094",
    rating: 4.9,
    tier: 1,
    stage: "new",
    status: "active",
    source: "research",
    notes: "High-rated practice in busy Centurion mall. Zero web/social presence. Purely reliant on walk-ins and word of mouth.",
    address: "Shop 18, Eldo Square Shopping Centre, Willem Botha Dr, Centurion",
    hours: "Tue-Thu: 8AM-5PM | Sat: 8AM-1PM",
    services: "General Dentistry",
    onlinePresence: "Google Maps only",
    recommendedPackage: "Crown (R8,999)",
    estimatedValue: 8999,
    hasWebsite: false,
    hotLead: true,
    nextAction: "Build ProtoLead demo, cold call with demo",
    nextActionDateDays: 3,
  },
  {
    name: "DR MOTHUPI DENTAL STUDIO",
    sector: "Dental",
    subSector: "General Dentistry",
    location: "Pretoria North",
    area: "Pretoria North",
    phone: "+27 79 927 4487",
    rating: 5.0,
    tier: 1,
    stage: "new",
    status: "active",
    source: "research",
    notes: "Perfect 5.0 rating. Saturday hours. B-BBEE angle works here. Community-serving clientele.",
    address: "404 West St, Pretoria North, 0116",
    hours: "Mon-Sat: 9AM-5PM",
    services: "General Dentistry",
    onlinePresence: "Google Maps only",
    recommendedPackage: "Molar (R4,499)",
    estimatedValue: 4499,
    hasWebsite: false,
    hotLead: true,
    nextAction: "Phone call - leverage B-BBEE angle",
    nextActionDateDays: 1,
  },
  {
    name: "Refresh Dental",
    sector: "Dental",
    subSector: "General Dentistry",
    location: "Centurion",
    area: "Lyttelton Manor",
    phone: "+27 61 416 4649",
    rating: 5.0,
    tier: 1,
    stage: "new",
    status: "active",
    source: "research",
    notes: "Perfect 5-star in affluent Lyttelton Manor. Premium market. Patients expect online booking capability.",
    address: "153 River Rd, Lyttelton Manor, Centurion, 0157",
    hours: "Mon-Fri: 9AM-5PM | Sat: 9AM-1PM",
    services: "General Dentistry",
    onlinePresence: "Google Maps only",
    recommendedPackage: "Crown (R8,999)",
    estimatedValue: 8999,
    hasWebsite: false,
    hotLead: true,
    nextAction: "Build ProtoLead demo for premium market",
    nextActionDateDays: 3,
  },
  {
    name: "Dr G Kellerman & Dr C Bosch Dentists",
    sector: "Dental",
    subSector: "General Dentistry",
    location: "Hatfield, Pretoria",
    area: "Hatfield",
    phone: "+27 12 342 3105",
    rating: 4.7,
    tier: 2,
    stage: "new",
    status: "active",
    source: "research",
    notes: "Two-practitioner practice. Student + professional market. Shared budget decision. Pitch as credibility + patient-acquisition.",
    address: "252 Grosvenor St, Hatfield, Pretoria, 0083",
    hours: "Mon-Thu: 7:30AM-4PM | Fri: 7:30AM-3:30PM",
    services: "General Dentistry",
    onlinePresence: "Google Maps only",
    recommendedPackage: "Crown (R8,999)",
    estimatedValue: 8999,
    hasWebsite: false,
    hotLead: false,
    nextAction: "Cold call - pitch to both practitioners",
    nextActionDateDays: undefined,
  },
  {
    name: "Dental Care Centre",
    sector: "Dental",
    subSector: "General Dentistry",
    location: "Pretoria North",
    area: "Pretoria North",
    phone: "+27 12 546 6863",
    rating: 4.7,
    tier: 2,
    stage: "new",
    status: "active",
    source: "research",
    notes: "Well-established at shopping centre intersection. Strong 4.7 rating.",
    address: "De Jongh Sentrum, c/o Rachel De Beer & Ben Viljoen St, Pta N 0182",
    hours: "Mon-Thu: 8AM-5PM | Fri: 8AM-4PM | Sat: 8AM-1PM",
    services: "General Dentistry",
    onlinePresence: "Google Maps only",
    recommendedPackage: "Crown (R8,999)",
    estimatedValue: 8999,
    hasWebsite: false,
    hotLead: false,
    nextAction: "Direct call with ROI pitch",
    nextActionDateDays: undefined,
  },
  {
    name: "Dr. Yolande Jordaan",
    sector: "Dental",
    subSector: "General Dentistry",
    location: "Pretoria East",
    area: "Faerie Glen",
    phone: "+27 12 004 2510",
    rating: 4.6,
    tier: 2,
    stage: "new",
    status: "active",
    source: "research",
    notes: "Affluent Faerie Glen. Patients research online. Need before/after photos, services, booking form.",
    address: "823 Old Farm Rd, Faerie Glen, Pretoria East, 0081",
    hours: "Mon/Wed: 8AM-4PM | Tue/Thu/Fri: 8AM-1PM",
    services: "General Dentistry",
    onlinePresence: "Google Maps, Polomap",
    recommendedPackage: "Crown (R8,999)",
    estimatedValue: 8999,
    hasWebsite: false,
    hotLead: false,
    nextAction: "Cold call - show before/after gallery demo",
    nextActionDateDays: undefined,
  },
  {
    name: "Dr Shaerah Mohamed",
    sector: "Dental",
    subSector: "General Dentistry",
    location: "Laudium, Pretoria",
    area: "Laudium",
    phone: "+27 12 374 6199",
    rating: 4.3,
    tier: 2,
    stage: "new",
    status: "active",
    source: "research",
    notes: "Shares premises with orthodontist who HAS website. Missing patient capture.",
    address: "290 Tangerine St, Laudium, Pretoria, 0037",
    hours: "Standard business hours",
    services: "General Dentistry",
    onlinePresence: "Google Maps",
    recommendedPackage: "Molar (R4,499)",
    estimatedValue: 4499,
    hasWebsite: false,
    hotLead: false,
    nextAction: "WhatsApp with competitor angle - neighbour has site",
    nextActionDateDays: undefined,
  },
  {
    name: "Dr ML Geldenhuys (Dental Surgeon)",
    sector: "Dental",
    subSector: "Dental Surgery",
    location: "Sunnyside, Pretoria",
    area: "Sunnyside",
    phone: "+27 12 430 4121",
    rating: 4.3,
    tier: 2,
    stage: "new",
    status: "active",
    source: "research",
    notes: "Full-spectrum surgeon in central Sunnyside. Website especially valuable for patients searching specific procedures.",
    address: "409 Kirkness St, Sunnyside, Pretoria, 0002",
    hours: "Standard weekday hours",
    services: "General, Cosmetic, Orthodontics, Dental Surgery",
    onlinePresence: "Google Maps, Snupit, WhoDoYou",
    recommendedPackage: "Crown (R8,999)",
    estimatedValue: 8999,
    hasWebsite: false,
    hotLead: false,
    nextAction: "Cold call - emphasize procedure-specific SEO value",
    nextActionDateDays: undefined,
  },
  {
    name: "Dr Vanessa Olckers",
    sector: "Dental",
    subSector: "General Dentistry",
    location: "Pretoria North",
    area: "Pretoria North",
    phone: "+27 12 546 0792",
    rating: 4.2,
    tier: 2,
    stage: "new",
    status: "active",
    source: "research",
    notes: "Medical-aid panel registered. Old Mutual patients search by name. No website = invisible to aid seekers.",
    address: "West Street Medical Centre, 240 Rachel de Beer St, Pta N 0182",
    hours: "Mon-Thu: 8AM-5PM | Fri: 8AM-3PM | Sat: 8AM-1PM",
    services: "General Dentistry",
    onlinePresence: "Old Mutual Dentistry Network, Google Maps",
    recommendedPackage: "Molar (R4,499)",
    estimatedValue: 4499,
    hasWebsite: false,
    hotLead: false,
    nextAction: "Cold call - medical aid patient acquisition angle",
    nextActionDateDays: undefined,
  },
  {
    name: "Dr F Khan / Smile Corner",
    sector: "Dental",
    subSector: "General Dentistry",
    location: "Laudium, Pretoria",
    area: "Laudium",
    phone: "Verify via Snupit",
    rating: 5.0,
    tier: 1,
    stage: "new",
    status: "active",
    source: "research",
    notes: "Perfect 5-star rating in Laudium. Community-oriented practice.",
    address: "Laudium, Pretoria",
    hours: "Standard business hours",
    services: "General Dentistry",
    onlinePresence: "Google Maps",
    recommendedPackage: "Molar (R4,499)",
    estimatedValue: 4499,
    hasWebsite: false,
    hotLead: true,
    nextAction: "Verify phone, then call",
    nextActionDateDays: undefined,
  },
  {
    name: "Nkwashu O A",
    sector: "Dental",
    subSector: "General Dentistry",
    location: "Atteridgeville",
    area: "Atteridgeville",
    phone: "Verify via Snupit",
    rating: 5.0,
    tier: 1,
    stage: "new",
    status: "active",
    source: "research",
    notes: "Perfect 5.0 rating in Atteridgeville. Community-serving practice.",
    address: "Atteridgeville / Saulsville",
    hours: "Standard business hours",
    services: "General Dentistry",
    onlinePresence: "Google Maps",
    recommendedPackage: "Molar (R4,499)",
    estimatedValue: 4499,
    hasWebsite: false,
    hotLead: true,
    nextAction: "Verify phone, then community approach",
    nextActionDateDays: undefined,
  },
  {
    name: "The Family Dentist",
    sector: "Dental",
    subSector: "Family Dentistry",
    location: "Pretoria East",
    area: "Faerie Glen",
    phone: "Verify via Snupit",
    rating: 4.4,
    tier: 2,
    stage: "new",
    status: "active",
    source: "research",
    notes: "Family branding in premium suburb. Parents book online, check hours, look for child-friendly environments.",
    address: "Faerie Glen, Pretoria East, 0081",
    hours: "Weekdays + possible Saturday",
    services: "Family Dentistry, General, Pediatric",
    onlinePresence: "Snupit listing only",
    recommendedPackage: "Crown (R8,999)",
    estimatedValue: 8999,
    hasWebsite: false,
    hotLead: false,
    nextAction: "Verify phone, demo with Kids Welcome section",
    nextActionDateDays: undefined,
  },
  {
    name: "Pretoria Smile",
    sector: "Dental",
    subSector: "Cosmetic Dentistry",
    location: "Queenswood, Pretoria",
    area: "Queenswood",
    phone: "Verify via Snupit",
    rating: 4.2,
    tier: 2,
    stage: "new",
    status: "active",
    source: "research",
    notes: "Cosmetic/smile focus. Portfolio website almost mandatory. Middle-to-upper income suburb.",
    address: "Queenswood, Pretoria",
    hours: "Standard business hours",
    services: "General Dentistry, Cosmetic Dentistry",
    onlinePresence: "Snupit listing only",
    recommendedPackage: "Crown (R8,999)",
    estimatedValue: 8999,
    hasWebsite: false,
    hotLead: false,
    nextAction: "Verify phone, pitch with before/after gallery",
    nextActionDateDays: undefined,
  },
  {
    name: "Dr Larochelle vd Bergh",
    sector: "Dental",
    subSector: "General Dentistry",
    location: "Queenswood, Pretoria",
    area: "Queenswood",
    phone: "Verify via Queenswood Medical Centre",
    rating: 4.0,
    tier: 2,
    stage: "new",
    status: "active",
    source: "research",
    notes: "New dentist within medical centre. Walk-in referrals from GPs. Needs independent patient base.",
    address: "Queenswood Medical Centre, Queenswood, Pretoria",
    hours: "Medical centre hours (Mon-Fri)",
    services: "General Dentistry",
    onlinePresence: "Snupit (via Queenswood Medical Centre)",
    recommendedPackage: "Molar (R4,499)",
    estimatedValue: 4499,
    hasWebsite: false,
    hotLead: false,
    nextAction: "Verify phone, then call",
    nextActionDateDays: undefined,
  },
  {
    name: "Dentist Consulting Rooms - Eloffsdal",
    sector: "Dental",
    subSector: "General Dentistry",
    location: "Eloffsdal, Pretoria",
    area: "Eloffsdal",
    phone: "Verify via Snupit",
    rating: 4.1,
    tier: 2,
    stage: "new",
    status: "active",
    source: "research",
    notes: "Adjacent to Pretoria North. Legacy practice not yet invested in digital.",
    address: "Eloffsdal, Pretoria",
    hours: "Standard weekday hours",
    services: "General Dentistry",
    onlinePresence: "Snupit directory only",
    recommendedPackage: "Molar (R4,499)",
    estimatedValue: 4499,
    hasWebsite: false,
    hotLead: false,
    nextAction: "Verify phone, outreach call",
    nextActionDateDays: undefined,
  },
  {
    name: "Dr Phalandwa",
    sector: "Dental",
    subSector: "General Dentistry",
    location: "Atteridgeville",
    area: "Atteridgeville",
    phone: "Verify via Snupit",
    rating: 4.3,
    tier: 2,
    stage: "new",
    status: "active",
    source: "research",
    notes: "Atteridgeville-based practice. Community-serving clientele.",
    address: "Atteridgeville / Saulsville",
    hours: "Standard business hours",
    services: "General Dentistry",
    onlinePresence: "Google Maps",
    recommendedPackage: "Molar (R4,499)",
    estimatedValue: 4499,
    hasWebsite: false,
    hotLead: false,
    nextAction: "Verify phone, then call",
    nextActionDateDays: undefined,
  },
  {
    name: "Dr Mahlase",
    sector: "Dental",
    subSector: "General Dentistry",
    location: "Pretoria East",
    area: "Faerie Glen",
    phone: "Verify via Snupit",
    rating: 3.9,
    tier: 3,
    stage: "new",
    status: "active",
    source: "research",
    notes: "Emerging practice in affluent area. Needs affordable entry point.",
    address: "Faerie Glen, Pretoria East",
    hours: "Standard business hours",
    services: "General Dentistry",
    onlinePresence: "Google Maps",
    recommendedPackage: "Molar (R4,499)",
    estimatedValue: 4499,
    hasWebsite: false,
    hotLead: false,
    nextAction: "Verify phone, pitch Molar package",
    nextActionDateDays: undefined,
  },
  {
    name: "Drs Behrens",
    sector: "Dental",
    subSector: "General Dentistry",
    location: "Atteridgeville",
    area: "Atteridgeville",
    phone: "Verify via Snupit",
    rating: 3.5,
    tier: 3,
    stage: "new",
    status: "active",
    source: "research",
    notes: "Lower rating in Atteridgeville. Affordable pitch needed.",
    address: "Atteridgeville / Saulsville",
    hours: "Standard business hours",
    services: "General Dentistry",
    onlinePresence: "Google Maps",
    recommendedPackage: "Molar (R4,499)",
    estimatedValue: 4499,
    hasWebsite: false,
    hotLead: false,
    nextAction: "Phone outreach, affordable pitch",
    nextActionDateDays: undefined,
  },
  {
    name: "Dr Olckers",
    sector: "Dental",
    subSector: "General Dentistry",
    location: "Pretoria North",
    area: "Pretoria North",
    phone: "+27 12 546 0792",
    rating: 4.2,
    tier: 2,
    stage: "new",
    status: "active",
    source: "research",
    notes: "Pretoria North practice with solid 4.2 rating.",
    address: "West Street Medical Centre, 240 Rachel de Beer St, Pta N",
    hours: "Mon-Thu: 8AM-5PM | Fri: 8AM-3PM | Sat: 8AM-1PM",
    services: "General Dentistry",
    onlinePresence: "Google Maps",
    recommendedPackage: "Molar (R4,499)",
    estimatedValue: 4499,
    hasWebsite: false,
    hotLead: false,
    nextAction: "Direct call",
    nextActionDateDays: undefined,
  },
]

// ====== MULTI-SECTOR LEADS (22-50) ======

const multiSectorLeadsRaw = [
  {
    name: "Matshona Attorneys",
    sector: "Legal",
    subSector: "Law Firm",
    location: "Pretoria CBD",
    area: "Pretoria CBD",
    phone: "+27 72 993 0963",
    rating: 4.9,
    tier: 1,
    stage: "new",
    status: "active",
    source: "research",
    notes: "TOP 5 PRIORITY. 4.9 rating, heart of CBD, Suit 428, 217 Pretorius St. Walk-in with printed mockup/brochure. Candidate for R20k+ corporate site.",
    address: "Suit 428, 217 Pretorius St, Pretoria CBD",
    hours: "Standard business hours",
    services: "Legal Services",
    onlinePresence: "Google Maps",
    recommendedPackage: "Khula (R7,999)",
    estimatedValue: 20000,
    hasWebsite: false,
    hotLead: true,
    nextAction: "Walk-in with printed mockup/brochure",
    nextActionDateDays: undefined,
  },
  {
    name: "TYAN Construction",
    sector: "Construction",
    subSector: "Construction",
    location: "Gauteng",
    area: "Gauteng",
    phone: "+27 11 493 3300",
    rating: 0,
    tier: 1,
    stage: "new",
    status: "active",
    source: "research",
    notes: "TOP 5 PRIORITY. Operating 24 hours, high-ticket projects, needs portfolio for tenders. Direct cold call to director/procurement manager.",
    address: "Gauteng",
    hours: "24 hours",
    services: "Construction Services",
    onlinePresence: "Google Maps",
    recommendedPackage: "Khula (R7,999)",
    estimatedValue: 25000,
    hasWebsite: false,
    hotLead: true,
    nextAction: "Direct cold call to director",
    nextActionDateDays: undefined,
  },
  {
    name: "CLC SA Commercial Logistics",
    sector: "Logistics",
    subSector: "Logistics",
    location: "Gauteng",
    area: "Gauteng",
    phone: "+27 86 122 2252",
    rating: 0,
    tier: 1,
    stage: "new",
    status: "active",
    source: "research",
    notes: "TOP 5 PRIORITY. Missing contact details online, frustrated reviewers, losing business. Cold call to operations manager.",
    address: "Gauteng",
    hours: "Standard business hours",
    services: "Commercial Logistics",
    onlinePresence: "Google Maps",
    recommendedPackage: "Vula (R3,999)",
    estimatedValue: 10000,
    hasWebsite: false,
    hotLead: true,
    nextAction: "Cold call to operations manager",
    nextActionDateDays: undefined,
  },
  {
    name: "The Thinc Clinic",
    sector: "Medical",
    subSector: "Dental Clinic",
    location: "Gauteng",
    area: "Gauteng",
    phone: "+27 11 788 6218",
    rating: 4.9,
    tier: 1,
    stage: "new",
    status: "active",
    source: "research",
    notes: "TOP 5 PRIORITY. 4.9 rating from 335 Google reviews, highly successful practice, no website. Estimated price tag: R30k-R50k.",
    address: "Gauteng",
    hours: "Standard business hours",
    services: "Dental Services",
    onlinePresence: "Google Maps (335 reviews)",
    recommendedPackage: "Implant (R16,999)",
    estimatedValue: 40000,
    hasWebsite: false,
    hotLead: true,
    nextAction: "Cold call receptionist, then tailored email/WhatsApp with Loom video mockup",
    nextActionDateDays: undefined,
  },
  {
    name: "Soweto Funeral Services",
    sector: "Funeral",
    subSector: "Funeral Home",
    location: "Soweto",
    area: "Soweto",
    phone: "+27 82 068 7015",
    rating: 0,
    tier: 1,
    stage: "new",
    status: "active",
    source: "research",
    notes: "TOP 5 PRIORITY. Highly lucrative industry, solid physical presence, zero digital footprint. WhatsApp message with respectful intro and demo link.",
    address: "Soweto",
    hours: "Standard business hours",
    services: "Funeral Services",
    onlinePresence: "Google Maps",
    recommendedPackage: "Vula (R3,999)",
    estimatedValue: 8000,
    hasWebsite: false,
    hotLead: true,
    nextAction: "WhatsApp message with respectful intro and demo link",
    nextActionDateDays: undefined,
  },
  {
    name: "Mfene Attorneys",
    sector: "Legal",
    subSector: "Legal Services",
    location: "Pretoria CBD",
    area: "Pretoria CBD",
    phone: "+27 12 321 2206",
    rating: 0,
    tier: 2,
    stage: "new",
    status: "active",
    source: "research",
    notes: "Pretoria CBD law firm. No website.",
    address: "Pretoria CBD",
    hours: "Standard business hours",
    services: "Legal Services",
    onlinePresence: "Google Maps",
    recommendedPackage: "Vula (R3,999)",
    estimatedValue: 7999,
    hasWebsite: false,
    hotLead: false,
    nextAction: "Cold call",
    nextActionDateDays: undefined,
  },
  {
    name: "SF Sibiya Attorneys",
    sector: "Legal",
    subSector: "Law Firm",
    location: "Pretoria CBD",
    area: "Pretoria CBD",
    phone: "N/A",
    rating: 0,
    tier: 2,
    stage: "new",
    status: "active",
    source: "research",
    notes: "Pretoria CBD law firm. No website. No phone listed - need to research.",
    address: "Pretoria CBD",
    hours: "Standard business hours",
    services: "Legal Services",
    onlinePresence: "Google Maps",
    recommendedPackage: "Vula (R3,999)",
    estimatedValue: 7999,
    hasWebsite: false,
    hotLead: false,
    nextAction: "Research phone number",
    nextActionDateDays: undefined,
  },
  {
    name: "Nthite Attorneys",
    sector: "Legal",
    subSector: "Law Firm",
    location: "Pretoria CBD",
    area: "Pretoria CBD",
    phone: "+27 76 308 3874",
    rating: 0,
    tier: 2,
    stage: "new",
    status: "active",
    source: "research",
    notes: "Pretoria CBD law firm. No website.",
    address: "Pretoria CBD",
    hours: "Standard business hours",
    services: "Legal Services",
    onlinePresence: "Google Maps",
    recommendedPackage: "Vula (R3,999)",
    estimatedValue: 7999,
    hasWebsite: false,
    hotLead: false,
    nextAction: "Cold call",
    nextActionDateDays: undefined,
  },
  {
    name: "The Resting View Guesthouse",
    sector: "Hospitality",
    subSector: "Guesthouse",
    location: "Pretoria East",
    area: "Pretoria East",
    phone: "N/A",
    rating: 0,
    tier: 2,
    stage: "new",
    status: "active",
    source: "research",
    notes: "Pretoria East guesthouse. No website - missing online booking revenue.",
    address: "Pretoria East",
    hours: "24 hours",
    services: "Guesthouse Accommodation",
    onlinePresence: "Google Maps",
    recommendedPackage: "Khula (R7,999)",
    estimatedValue: 7999,
    hasWebsite: false,
    hotLead: false,
    nextAction: "Research phone, then call",
    nextActionDateDays: undefined,
  },
  {
    name: "Camellia Haven",
    sector: "Hospitality",
    subSector: "Guest House",
    location: "Pretoria East",
    area: "Pretoria East",
    phone: "N/A",
    rating: 0,
    tier: 2,
    stage: "new",
    status: "active",
    source: "research",
    notes: "Pretoria East guest house. No website.",
    address: "Pretoria East",
    hours: "24 hours",
    services: "Guesthouse Accommodation",
    onlinePresence: "Google Maps",
    recommendedPackage: "Khula (R7,999)",
    estimatedValue: 7999,
    hasWebsite: false,
    hotLead: false,
    nextAction: "Research phone, then call",
    nextActionDateDays: undefined,
  },
  {
    name: "Mabona Funeral Undertakers",
    sector: "Funeral",
    subSector: "Funeral Home",
    location: "Soweto",
    area: "Soweto",
    phone: "+27 11 936 9000",
    rating: 0,
    tier: 2,
    stage: "new",
    status: "active",
    source: "research",
    notes: "Soweto funeral home. Established presence, no digital footprint.",
    address: "Soweto",
    hours: "Standard business hours",
    services: "Funeral Services",
    onlinePresence: "Google Maps",
    recommendedPackage: "Vula (R3,999)",
    estimatedValue: 5999,
    hasWebsite: false,
    hotLead: false,
    nextAction: "WhatsApp outreach",
    nextActionDateDays: undefined,
  },
  {
    name: "Kwa Ndhlovu And Sons Funerals",
    sector: "Funeral",
    subSector: "Funeral Home",
    location: "Soweto",
    area: "Soweto",
    phone: "+27 82 740 2336",
    rating: 0,
    tier: 2,
    stage: "new",
    status: "active",
    source: "research",
    notes: "Soweto funeral home. Family business, no digital footprint.",
    address: "Soweto",
    hours: "Standard business hours",
    services: "Funeral Services",
    onlinePresence: "Google Maps",
    recommendedPackage: "Vula (R3,999)",
    estimatedValue: 5999,
    hasWebsite: false,
    hotLead: false,
    nextAction: "WhatsApp outreach with respectful tone",
    nextActionDateDays: undefined,
  },
  {
    name: "Awethu Funeral Directors",
    sector: "Funeral",
    subSector: "Funeral Home",
    location: "Soweto",
    area: "Soweto",
    phone: "+27 79 257 6600",
    rating: 0,
    tier: 2,
    stage: "new",
    status: "active",
    source: "research",
    notes: "Soweto funeral directors. No digital footprint.",
    address: "Soweto",
    hours: "Standard business hours",
    services: "Funeral Services",
    onlinePresence: "Google Maps",
    recommendedPackage: "Vula (R3,999)",
    estimatedValue: 5999,
    hasWebsite: false,
    hotLead: false,
    nextAction: "WhatsApp outreach",
    nextActionDateDays: undefined,
  },
  {
    name: "RB & Son Transport Gauteng CC",
    sector: "Logistics",
    subSector: "Transportation",
    location: "Gauteng",
    area: "Gauteng",
    phone: "+27 11 974 5984",
    rating: 0,
    tier: 2,
    stage: "new",
    status: "active",
    source: "research",
    notes: "Gauteng transport company. No website.",
    address: "Gauteng",
    hours: "Standard business hours",
    services: "Transportation",
    onlinePresence: "Google Maps",
    recommendedPackage: "Vula (R3,999)",
    estimatedValue: 5999,
    hasWebsite: false,
    hotLead: false,
    nextAction: "Cold call",
    nextActionDateDays: undefined,
  },
  {
    name: "No Boundaries Logistics",
    sector: "Logistics",
    subSector: "Freight Forward",
    location: "Gauteng",
    area: "Gauteng",
    phone: "+27 67 178 9297",
    rating: 0,
    tier: 2,
    stage: "new",
    status: "active",
    source: "research",
    notes: "Gauteng freight forwarder. No website.",
    address: "Gauteng",
    hours: "Standard business hours",
    services: "Freight Forwarding",
    onlinePresence: "Google Maps",
    recommendedPackage: "Vula (R3,999)",
    estimatedValue: 5999,
    hasWebsite: false,
    hotLead: false,
    nextAction: "Cold call",
    nextActionDateDays: undefined,
  },
  {
    name: "Sanjo Construction",
    sector: "Construction",
    subSector: "Construction",
    location: "Gauteng",
    area: "Gauteng",
    phone: "+27 86 117 2656",
    rating: 0,
    tier: 2,
    stage: "new",
    status: "active",
    source: "research",
    notes: "Gauteng construction firm. Needs portfolio website for tenders.",
    address: "Gauteng",
    hours: "Standard business hours",
    services: "Construction Services",
    onlinePresence: "Google Maps",
    recommendedPackage: "Khula (R7,999)",
    estimatedValue: 15000,
    hasWebsite: false,
    hotLead: false,
    nextAction: "Cold call with portfolio angle",
    nextActionDateDays: undefined,
  },
  {
    name: "Cross Over School",
    sector: "Education",
    subSector: "Private School",
    location: "Gauteng",
    area: "Gauteng",
    phone: "+27 10 534 7495",
    rating: 0,
    tier: 2,
    stage: "new",
    status: "active",
    source: "research",
    notes: "Private school. Needs Presenca or Ikredibo package.",
    address: "Gauteng",
    hours: "Standard school hours",
    services: "Education",
    onlinePresence: "Google Maps",
    recommendedPackage: "Presenca (R4,999)",
    estimatedValue: 9999,
    hasWebsite: false,
    hotLead: false,
    nextAction: "Cold call with school-specific pitch",
    nextActionDateDays: undefined,
  },
  {
    name: "Japari School",
    sector: "Education",
    subSector: "Private School",
    location: "Gauteng",
    area: "Gauteng",
    phone: "+27 11 646 2132",
    rating: 0,
    tier: 2,
    stage: "new",
    status: "active",
    source: "research",
    notes: "Private school. Strong candidate for school package.",
    address: "Gauteng",
    hours: "Standard school hours",
    services: "Education",
    onlinePresence: "Google Maps",
    recommendedPackage: "Ikredibo (R9,999)",
    estimatedValue: 9999,
    hasWebsite: false,
    hotLead: false,
    nextAction: "Cold call with school-specific pitch",
    nextActionDateDays: undefined,
  },
  {
    name: "Brandcliff House Private School",
    sector: "Education",
    subSector: "Private School",
    location: "Gauteng",
    area: "Gauteng",
    phone: "+27 11 476 4174",
    rating: 0,
    tier: 2,
    stage: "new",
    status: "active",
    source: "research",
    notes: "Private school. No website.",
    address: "Gauteng",
    hours: "Standard school hours",
    services: "Education",
    onlinePresence: "Google Maps",
    recommendedPackage: "Presenca (R4,999)",
    estimatedValue: 9999,
    hasWebsite: false,
    hotLead: false,
    nextAction: "Cold call with school-specific pitch",
    nextActionDateDays: undefined,
  },
  {
    name: "Poplar Academy",
    sector: "Education",
    subSector: "Private School",
    location: "Gauteng",
    area: "Gauteng",
    phone: "+27 82 655 0723",
    rating: 0,
    tier: 2,
    stage: "new",
    status: "active",
    source: "research",
    notes: "Private school. No website.",
    address: "Gauteng",
    hours: "Standard school hours",
    services: "Education",
    onlinePresence: "Google Maps",
    recommendedPackage: "Presenca (R4,999)",
    estimatedValue: 9999,
    hasWebsite: false,
    hotLead: false,
    nextAction: "Cold call with school-specific pitch",
    nextActionDateDays: undefined,
  },
  {
    name: "The Medical Centre",
    sector: "Medical",
    subSector: "Medical Center",
    location: "Gauteng",
    area: "Gauteng",
    phone: "+27 11 622 6254",
    rating: 0,
    tier: 2,
    stage: "new",
    status: "active",
    source: "research",
    notes: "Medical centre. No website.",
    address: "Gauteng",
    hours: "Standard business hours",
    services: "Medical Services",
    onlinePresence: "Google Maps",
    recommendedPackage: "Khula (R7,999)",
    estimatedValue: 7999,
    hasWebsite: false,
    hotLead: false,
    nextAction: "Cold call",
    nextActionDateDays: undefined,
  },
  {
    name: "Cosmo City Dental Centre",
    sector: "Dental",
    subSector: "Dental Clinic",
    location: "Gauteng",
    area: "Gauteng",
    phone: "+27 61 524 2458",
    rating: 0,
    tier: 2,
    stage: "new",
    status: "active",
    source: "research",
    notes: "Dental clinic in Cosmo City area. No website.",
    address: "Gauteng",
    hours: "Standard business hours",
    services: "General Dentistry",
    onlinePresence: "Google Maps",
    recommendedPackage: "Molar (R4,499)",
    estimatedValue: 4499,
    hasWebsite: false,
    hotLead: false,
    nextAction: "Cold call",
    nextActionDateDays: undefined,
  },
  {
    name: "Eden Dental Centre",
    sector: "Dental",
    subSector: "Dental Clinic",
    location: "Gauteng",
    area: "Gauteng",
    phone: "+27 11 453 7612",
    rating: 0,
    tier: 2,
    stage: "new",
    status: "active",
    source: "research",
    notes: "Dental clinic. No website.",
    address: "Gauteng",
    hours: "Standard business hours",
    services: "General Dentistry",
    onlinePresence: "Google Maps",
    recommendedPackage: "Molar (R4,499)",
    estimatedValue: 4499,
    hasWebsite: false,
    hotLead: false,
    nextAction: "Cold call",
    nextActionDateDays: undefined,
  },
  {
    name: "PTA East Guest Rooms",
    sector: "Hospitality",
    subSector: "Hospitality",
    location: "Pretoria East",
    area: "Pretoria East",
    phone: "N/A",
    rating: 0,
    tier: 2,
    stage: "new",
    status: "active",
    source: "research",
    notes: "Pretoria East guest rooms. No website.",
    address: "Pretoria East",
    hours: "24 hours",
    services: "Guest Accommodation",
    onlinePresence: "Google Maps",
    recommendedPackage: "Vula (R3,999)",
    estimatedValue: 3999,
    hasWebsite: false,
    hotLead: false,
    nextAction: "Research phone",
    nextActionDateDays: undefined,
  },
  {
    name: "Dr. Cajee (Parkstation)",
    sector: "Medical",
    subSector: "General Practitioner",
    location: "Gauteng",
    area: "Gauteng",
    phone: "+27 11 333 4597",
    rating: 0,
    tier: 2,
    stage: "new",
    status: "active",
    source: "research",
    notes: "General practitioner. No website.",
    address: "Gauteng",
    hours: "Standard business hours",
    services: "General Practice",
    onlinePresence: "Google Maps",
    recommendedPackage: "Vula (R3,999)",
    estimatedValue: 3999,
    hasWebsite: false,
    hotLead: false,
    nextAction: "Cold call",
    nextActionDateDays: undefined,
  },
  {
    name: "Dr H Haffejee",
    sector: "Medical",
    subSector: "General Practitioner",
    location: "Gauteng",
    area: "Gauteng",
    phone: "+27 11 834 1554",
    rating: 0,
    tier: 2,
    stage: "new",
    status: "active",
    source: "research",
    notes: "General practitioner. No website.",
    address: "Gauteng",
    hours: "Standard business hours",
    services: "General Practice",
    onlinePresence: "Google Maps",
    recommendedPackage: "Vula (R3,999)",
    estimatedValue: 3999,
    hasWebsite: false,
    hotLead: false,
    nextAction: "Cold call",
    nextActionDateDays: undefined,
  },
  {
    name: "Dr Marlin J McKay",
    sector: "Medical",
    subSector: "Medical Center",
    location: "Gauteng",
    area: "Gauteng",
    phone: "+27 11 672 2129",
    rating: 0,
    tier: 2,
    stage: "new",
    status: "active",
    source: "research",
    notes: "Medical centre. No website.",
    address: "Gauteng",
    hours: "Standard business hours",
    services: "Medical Services",
    onlinePresence: "Google Maps",
    recommendedPackage: "Khula (R7,999)",
    estimatedValue: 7999,
    hasWebsite: false,
    hotLead: false,
    nextAction: "Cold call",
    nextActionDateDays: undefined,
  },
  {
    name: "Cahi Dental Practice",
    sector: "Dental",
    subSector: "Dentist",
    location: "Gauteng",
    area: "Gauteng",
    phone: "+27 11 305 9300",
    rating: 0,
    tier: 2,
    stage: "new",
    status: "active",
    source: "research",
    notes: "Dental practice. No website.",
    address: "Gauteng",
    hours: "Standard business hours",
    services: "General Dentistry",
    onlinePresence: "Google Maps",
    recommendedPackage: "Molar (R4,499)",
    estimatedValue: 4499,
    hasWebsite: false,
    hotLead: false,
    nextAction: "Cold call",
    nextActionDateDays: undefined,
  },
  {
    name: "Molar Bear Dental",
    sector: "Dental",
    subSector: "Dentist",
    location: "Gauteng",
    area: "Gauteng",
    phone: "+27 11 482 1592",
    rating: 0,
    tier: 2,
    stage: "new",
    status: "active",
    source: "research",
    notes: "Dental practice. No website.",
    address: "Gauteng",
    hours: "Standard business hours",
    services: "General Dentistry",
    onlinePresence: "Google Maps",
    recommendedPackage: "Molar (R4,499)",
    estimatedValue: 4499,
    hasWebsite: false,
    hotLead: false,
    nextAction: "Cold call",
    nextActionDateDays: undefined,
  },
  {
    name: "Ziyaad Dental Surgery",
    sector: "Dental",
    subSector: "Dental Clinic",
    location: "Gauteng",
    area: "Gauteng",
    phone: "+27 11 403 6786",
    rating: 0,
    tier: 2,
    stage: "new",
    status: "active",
    source: "research",
    notes: "Dental surgery. No website.",
    address: "Gauteng",
    hours: "Standard business hours",
    services: "Dental Surgery",
    onlinePresence: "Google Maps",
    recommendedPackage: "Crown (R8,999)",
    estimatedValue: 8999,
    hasWebsite: false,
    hotLead: false,
    nextAction: "Cold call",
    nextActionDateDays: undefined,
  },
]

// ====== BUILD LEAD RECORDS ======

const allLeadsRaw = [...dentalLeadsRaw, ...multiSectorLeadsRaw]

export const SEED_LEADS: LeadRecord[] = allLeadsRaw.map((lead, i) => ({
  id: cuid(i + 1),
  name: lead.name,
  sector: lead.sector,
  subSector: lead.subSector || "",
  location: lead.location,
  area: lead.area || "",
  phone: lead.phone || "",
  rating: lead.rating ?? 0,
  tier: lead.tier ?? 3,
  stage: lead.stage || "new",
  status: lead.status || "active",
  source: lead.source || "research",
  notes: lead.notes || "",
  address: lead.address || "",
  hours: lead.hours || "",
  services: lead.services || "",
  onlinePresence: lead.onlinePresence || "",
  recommendedPackage: lead.recommendedPackage || "",
  estimatedValue: lead.estimatedValue ?? 0,
  hasWebsite: lead.hasWebsite ?? false,
  lastContact: null,
  nextAction: lead.nextAction || "",
  nextActionDate: lead.nextActionDateDays != null ? iso(lead.nextActionDateDays) : null,
  hotLead: lead.hotLead ?? false,
  createdAt: iso(-30 + Math.floor(i / 5)),  // staggered over past 30 days
  updatedAt: iso(0),
}))

// ====== ACTIVITY DATA ======

const activitiesRaw = [
  { leadName: "Dr. Elaine de Lange Dentist", type: "note", summary: "Identified as highest priority dental lead. 4.9 rating, 562 Facebook likes, no website.", outcome: "Ready for ProtoLead demo build" },
  { leadName: "The Thinc Clinic", type: "note", summary: "335 Google reviews with 4.9 rating. Highly successful practice. Estimated R30k-R50k project.", outcome: "Prepare Loom video mockup" },
  { leadName: "Matshona Attorneys", type: "note", summary: "4.9 rating in heart of Pretoria CBD. Suit 428, 217 Pretorius St.", outcome: "Prepare printed mockup for walk-in" },
  { leadName: "DR MOTHUPI DENTAL STUDIO", type: "note", summary: "Perfect 5.0 rating. Saturday hours. B-BBEE angle strong here.", outcome: "Leverage B-BBEE Level 1 status in pitch" },
  { leadName: "Refresh Dental", type: "note", summary: "Perfect 5-star in affluent Lyttelton Manor. Premium market expectations.", outcome: "Build premium ProtoLead demo" },
]

export const SEED_ACTIVITIES: ActivityRecord[] = activitiesRaw.map((act, i) => {
  const lead = SEED_LEADS.find((l) => l.name === act.leadName)
  return {
    id: cuid(100 + i),
    leadId: lead?.id || "",
    type: act.type,
    summary: act.summary,
    outcome: act.outcome,
    date: iso(-1 - i),
    lead: lead ? { id: lead.id, name: lead.name } : undefined,
    createdAt: iso(-1 - i),
  }
})

// ====== CAMPAIGN DATA ======

export const SEED_CAMPAIGNS: CampaignRecord[] = [
  {
    id: cuid(200),
    name: "Dental Practices - Pretoria Blitz",
    type: "cold-email",
    status: "active",
    targetSector: "Dental",
    message: "Hi {name}, I noticed your practice has fantastic reviews on Google but no website. We help dentists in Pretoria get a professional online presence that converts patients. Would you be open to a 10-min chat?",
    emailsSent: 15,
    openRate: 42.3,
    responseRate: 18.7,
    createdAt: iso(-7),
    updatedAt: iso(0),
  },
  {
    id: cuid(201),
    name: "Soweto Funeral Homes Outreach",
    type: "whatsapp",
    status: "draft",
    targetSector: "Funeral",
    message: "Good day. I represent Carter Digitals. We build websites that help families find your services when they need them most. Can I send you a quick demo?",
    emailsSent: 0,
    openRate: 0,
    responseRate: 0,
    createdAt: iso(-3),
    updatedAt: iso(-1),
  },
  {
    id: cuid(202),
    name: "Gauteng Schools Package",
    type: "cold-email",
    status: "active",
    targetSector: "Education",
    message: "Hello {name}, parents are searching for schools online more than ever. Is your school easy to find? We build enrollment-ready websites for private schools starting at R4,999/mo.",
    emailsSent: 8,
    openRate: 37.5,
    responseRate: 12.5,
    createdAt: iso(-5),
    updatedAt: iso(0),
  },
  {
    id: cuid(203),
    name: "Legal Firms - CBD Campaign",
    type: "linkedin",
    status: "paused",
    targetSector: "Legal",
    message: "Hi {name}, noticed your firm doesn't have a web presence. We specialize in building credibility-focused websites for law firms in Pretoria.",
    emailsSent: 22,
    openRate: 31.8,
    responseRate: 9.1,
    createdAt: iso(-14),
    updatedAt: iso(-2),
  },
]

// ====== HELPER FUNCTIONS ======

export interface LeadFilters {
  sector?: string | null
  tier?: string | null
  stage?: string | null
  status?: string | null
  hotLead?: string | null
  search?: string | null
}

export function getFallbackStats() {
  const leads = SEED_LEADS

  const totalLeads = leads.length
  const hotLeads = leads.filter((l) => l.hotLead).length
  const dentalLeads = leads.filter((l) => l.sector === "Dental").length

  const activeLeads = leads.filter(
    (l) => l.status === "active" && l.stage !== "won" && l.stage !== "lost"
  )
  const pipelineValue = activeLeads.reduce((sum, l) => sum + (l.estimatedValue || 0), 0)

  const wonLeads = leads.filter((l) => l.stage === "won").length
  const conversionRate = totalLeads > 0 ? Math.round((wonLeads / totalLeads) * 100) : 0

  // By sector
  const sectorMap: Record<string, number> = {}
  leads.forEach((l) => {
    sectorMap[l.sector] = (sectorMap[l.sector] || 0) + 1
  })
  const bySector = Object.entries(sectorMap)
    .map(([sector, count]) => ({ sector, count }))
    .sort((a, b) => b.count - a.count)

  // By tier
  const tierMap: Record<string, number> = {}
  leads.forEach((l) => {
    const key = `Tier ${l.tier}`
    tierMap[key] = (tierMap[key] || 0) + 1
  })
  const byTier = [
    { tier: "Tier 1", count: tierMap["Tier 1"] || 0 },
    { tier: "Tier 2", count: tierMap["Tier 2"] || 0 },
    { tier: "Tier 3", count: tierMap["Tier 3"] || 0 },
  ]

  // By stage
  const stages = [
    "new",
    "contacted",
    "demo_sent",
    "meeting_booked",
    "proposal_sent",
    "negotiation",
    "won",
    "lost",
  ]
  const stageLabels: Record<string, string> = {
    new: "New",
    contacted: "Contacted",
    demo_sent: "Demo Sent",
    meeting_booked: "Meeting Booked",
    proposal_sent: "Proposal Sent",
    negotiation: "Negotiation",
    won: "Won",
    lost: "Lost",
  }
  const byStage = stages.map((stage) => ({
    stage,
    label: stageLabels[stage],
    count: leads.filter((l) => l.stage === stage).length,
  }))

  // Recent activities with lead info (matches Prisma include shape)
  const recentActivities = SEED_ACTIVITIES
    .map((act) => ({
      ...act,
      lead: SEED_LEADS.find((l) => l.id === act.leadId)
        ? { id: act.leadId, name: SEED_LEADS.find((l) => l.id === act.leadId)!.name }
        : { id: act.leadId, name: "Unknown" },
    }))
    .sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime())
    .slice(0, 10)

  return {
    totalLeads,
    hotLeads,
    dentalLeads,
    pipelineValue,
    conversionRate,
    bySector,
    byTier,
    byStage,
    recentActivities,
    activePipeline: activeLeads.length,
    wonLeads,
    lostLeads: leads.filter((l) => l.stage === "lost").length,
  }
}

export function getFallbackLeads(filters: LeadFilters = {}): LeadRecord[] {
  let leads = [...SEED_LEADS]

  if (filters.sector) {
    leads = leads.filter((l) => l.sector === filters.sector)
  }
  if (filters.tier) {
    const tierNum = parseInt(filters.tier)
    if (!isNaN(tierNum)) leads = leads.filter((l) => l.tier === tierNum)
  }
  if (filters.stage) {
    leads = leads.filter((l) => l.stage === filters.stage)
  }
  if (filters.status) {
    leads = leads.filter((l) => l.status === filters.status)
  }
  if (filters.hotLead === "true") {
    leads = leads.filter((l) => l.hotLead === true)
  } else if (filters.hotLead === "false") {
    leads = leads.filter((l) => l.hotLead === false)
  }
  if (filters.search) {
    const s = filters.search.toLowerCase()
    leads = leads.filter(
      (l) =>
        l.name.toLowerCase().includes(s) ||
        l.sector.toLowerCase().includes(s) ||
        l.location.toLowerCase().includes(s) ||
        l.area.toLowerCase().includes(s)
    )
  }

  // Attach activities (matching Prisma include shape)
  return leads
    .map((lead) => ({
      ...lead,
      activities: SEED_ACTIVITIES
        .filter((a) => a.leadId === lead.id)
        .slice(0, 3),
    }))
    .sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime())
}

export function getFallbackLead(id: string): LeadRecord | null {
  const lead = SEED_LEADS.find((l) => l.id === id)
  if (!lead) return null

  return {
    ...lead,
    activities: SEED_ACTIVITIES.filter((a) => a.leadId === lead.id),
  }
}

export function getFallbackCampaigns(): CampaignRecord[] {
  return [...SEED_CAMPAIGNS].sort(
    (a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime()
  )
}
