import { db } from '@/lib/db';
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  // Clear existing data
  await prisma.activity.deleteMany();
  await prisma.lead.deleteMany();

  // ====== DENTAL LEADS FROM FILE 4 (Pretoria & Centurion) ======
  const dentalLeads = [
    {
      name: "Dr. Elaine de Lange Dentist",
      sector: "Dental",
      subSector: "General & Cosmetic Dentistry",
      location: "Hatfield, Pretoria",
      area: "Hatfield",
      phone: "+27 67 163 8738",
      rating: 4.9,
      tier: 1,
      stage: "new",
      status: "active",
      source: "research",
      notes: "SINGLE HIGHEST-PRIORITY LEAD. Glowing reviews for root canal work and pregnancy care. Built audience, zero digital home. Conversion-ready prospect. Facebook (562 likes, 9 check-ins), Medpages, Old Mutual, Polomap.",
      address: "Hatfield Wellness Centre, 454 Hilda St, Hatfield, 0028",
      hours: "Mon/Wed: 8AM-4PM | Tue/Thu/Fri: 8AM-1PM",
      services: "General Dentistry, Cosmetic, Dental Hygiene, Pediatric",
      onlinePresence: "Facebook (562 likes), Medpages, Old Mutual, Polomap",
      recommendedPackage: "Crown (R8,999)",
      estimatedValue: 8999,
      hasWebsite: false,
      hotLead: true,
      nextAction: "Build ProtoLead demo site, then call receptionist",
      nextActionDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000),
    },
    {
      name: "The Dental Doc (Dr Mythili Swaminathan)",
      sector: "Dental",
      subSector: "General Dentistry",
      location: "Centurion",
      area: "Eldoraigne",
      phone: "+27 12 658 3094",
      rating: 4.9,
      tier: 1,
      stage: "new",
      status: "active",
      source: "research",
      notes: "High-rated practice in busy Centurion mall. Zero web/social presence. Purely reliant on walk-ins and word of mouth.",
      address: "Shop 18, Eldo Square Shopping Centre, Willem Botha Dr, Centurion",
      hours: "Tue-Thu: 8AM-5PM | Sat: 8AM-1PM",
      services: "General Dentistry",
      onlinePresence: "Google Maps only",
      recommendedPackage: "Crown (R8,999)",
      estimatedValue: 8999,
      hasWebsite: false,
      hotLead: true,
      nextAction: "Build ProtoLead demo, cold call with demo",
      nextActionDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000),
    },
    {
      name: "DR MOTHUPI DENTAL STUDIO",
      sector: "Dental",
      subSector: "General Dentistry",
      location: "Pretoria North",
      area: "Pretoria North",
      phone: "+27 79 927 4487",
      rating: 5.0,
      tier: 1,
      stage: "new",
      status: "active",
      source: "research",
      notes: "Perfect 5.0 rating. Saturday hours. B-BBEE angle works here. Community-serving clientele.",
      address: "404 West St, Pretoria North, 0116",
      hours: "Mon-Sat: 9AM-5PM",
      services: "General Dentistry",
      onlinePresence: "Google Maps only",
      recommendedPackage: "Molar (R4,499)",
      estimatedValue: 4499,
      hasWebsite: false,
      hotLead: true,
      nextAction: "Phone call - leverage B-BBEE angle",
      nextActionDate: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000),
    },
    {
      name: "Refresh Dental",
      sector: "Dental",
      subSector: "General Dentistry",
      location: "Centurion",
      area: "Lyttelton Manor",
      phone: "+27 61 416 4649",
      rating: 5.0,
      tier: 1,
      stage: "new",
      status: "active",
      source: "research",
      notes: "Perfect 5-star in affluent Lyttelton Manor. Premium market. Patients expect online booking capability.",
      address: "153 River Rd, Lyttelton Manor, Centurion, 0157",
      hours: "Mon-Fri: 9AM-5PM | Sat: 9AM-1PM",
      services: "General Dentistry",
      onlinePresence: "Google Maps only",
      recommendedPackage: "Crown (R8,999)",
      estimatedValue: 8999,
      hasWebsite: false,
      hotLead: true,
      nextAction: "Build ProtoLead demo for premium market",
      nextActionDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000),
    },
    {
      name: "Dr G Kellerman & Dr C Bosch Dentists",
      sector: "Dental",
      subSector: "General Dentistry",
      location: "Hatfield, Pretoria",
      area: "Hatfield",
      phone: "+27 12 342 3105",
      rating: 4.7,
      tier: 2,
      stage: "new",
      status: "active",
      source: "research",
      notes: "Two-practitioner practice. Student + professional market. Shared budget decision. Pitch as credibility + patient-acquisition.",
      address: "252 Grosvenor St, Hatfield, Pretoria, 0083",
      hours: "Mon-Thu: 7:30AM-4PM | Fri: 7:30AM-3:30PM",
      services: "General Dentistry",
      onlinePresence: "Google Maps only",
      recommendedPackage: "Crown (R8,999)",
      estimatedValue: 8999,
      hasWebsite: false,
      nextAction: "Cold call - pitch to both practitioners",
    },
    {
      name: "Dental Care Centre",
      sector: "Dental",
      subSector: "General Dentistry",
      location: "Pretoria North",
      area: "Pretoria North",
      phone: "+27 12 546 6863",
      rating: 4.7,
      tier: 2,
      stage: "new",
      status: "active",
      source: "research",
      notes: "Well-established at shopping centre intersection. Strong 4.7 rating.",
      address: "De Jongh Sentrum, c/o Rachel De Beer & Ben Viljoen St, Pta N 0182",
      hours: "Mon-Thu: 8AM-5PM | Fri: 8AM-4PM | Sat: 8AM-1PM",
      services: "General Dentistry",
      onlinePresence: "Google Maps only",
      recommendedPackage: "Crown (R8,999)",
      estimatedValue: 8999,
      hasWebsite: false,
      nextAction: "Direct call with ROI pitch",
    },
    {
      name: "Dr. Yolande Jordaan",
      sector: "Dental",
      subSector: "General Dentistry",
      location: "Pretoria East",
      area: "Faerie Glen",
      phone: "+27 12 004 2510",
      rating: 4.6,
      tier: 2,
      stage: "new",
      status: "active",
      source: "research",
      notes: "Affluent Faerie Glen. Patients research online. Need before/after photos, services, booking form.",
      address: "823 Old Farm Rd, Faerie Glen, Pretoria East, 0081",
      hours: "Mon/Wed: 8AM-4PM | Tue/Thu/Fri: 8AM-1PM",
      services: "General Dentistry",
      onlinePresence: "Google Maps, Polomap",
      recommendedPackage: "Crown (R8,999)",
      estimatedValue: 8999,
      hasWebsite: false,
      nextAction: "Cold call - show before/after gallery demo",
    },
    {
      name: "Dr Shaerah Mohamed",
      sector: "Dental",
      subSector: "General Dentistry",
      location: "Laudium, Pretoria",
      area: "Laudium",
      phone: "+27 12 374 6199",
      rating: 4.3,
      tier: 2,
      stage: "new",
      status: "active",
      source: "research",
      notes: "Shares premises with orthodontist who HAS website. Missing patient capture.",
      address: "290 Tangerine St, Laudium, Pretoria, 0037",
      hours: "Standard business hours",
      services: "General Dentistry",
      onlinePresence: "Google Maps",
      recommendedPackage: "Molar (R4,499)",
      estimatedValue: 4499,
      hasWebsite: false,
      nextAction: "WhatsApp with competitor angle - neighbour has site",
    },
    {
      name: "Dr ML Geldenhuys (Dental Surgeon)",
      sector: "Dental",
      subSector: "Dental Surgery",
      location: "Sunnyside, Pretoria",
      area: "Sunnyside",
      phone: "+27 12 430 4121",
      rating: 4.3,
      tier: 2,
      stage: "new",
      status: "active",
      source: "research",
      notes: "Full-spectrum surgeon in central Sunnyside. Website especially valuable for patients searching specific procedures.",
      address: "409 Kirkness St, Sunnyside, Pretoria, 0002",
      hours: "Standard weekday hours",
      services: "General, Cosmetic, Orthodontics, Dental Surgery",
      onlinePresence: "Google Maps, Snupit, WhoDoYou",
      recommendedPackage: "Crown (R8,999)",
      estimatedValue: 8999,
      hasWebsite: false,
      nextAction: "Cold call - emphasize procedure-specific SEO value",
    },
    {
      name: "Dr Vanessa Olckers",
      sector: "Dental",
      subSector: "General Dentistry",
      location: "Pretoria North",
      area: "Pretoria North",
      phone: "+27 12 546 0792",
      rating: 4.2,
      tier: 2,
      stage: "new",
      status: "active",
      source: "research",
      notes: "Medical-aid panel registered. Old Mutual patients search by name. No website = invisible to aid seekers.",
      address: "West Street Medical Centre, 240 Rachel de Beer St, Pta N 0182",
      hours: "Mon-Thu: 8AM-5PM | Fri: 8AM-3PM | Sat: 8AM-1PM",
      services: "General Dentistry",
      onlinePresence: "Old Mutual Dentistry Network, Google Maps",
      recommendedPackage: "Molar (R4,499)",
      estimatedValue: 4499,
      hasWebsite: false,
      nextAction: "Cold call - medical aid patient acquisition angle",
    },
    {
      name: "Dr F Khan / Smile Corner",
      sector: "Dental",
      subSector: "General Dentistry",
      location: "Laudium, Pretoria",
      area: "Laudium",
      phone: "Verify via Snupit",
      rating: 5.0,
      tier: 1,
      stage: "new",
      status: "active",
      source: "research",
      notes: "Perfect 5-star rating in Laudium. Community-oriented practice.",
      address: "Laudium, Pretoria",
      hours: "Standard business hours",
      services: "General Dentistry",
      onlinePresence: "Google Maps",
      recommendedPackage: "Molar (R4,499)",
      estimatedValue: 4499,
      hasWebsite: false,
      nextAction: "Verify phone, then call",
    },
    {
      name: "Nkwashu O A",
      sector: "Dental",
      subSector: "General Dentistry",
      location: "Atteridgeville",
      area: "Atteridgeville",
      phone: "Verify via Snupit",
      rating: 5.0,
      tier: 1,
      stage: "new",
      status: "active",
      source: "research",
      notes: "Perfect 5.0 rating in Atteridgeville. Community-serving practice.",
      address: "Atteridgeville / Saulsville",
      hours: "Standard business hours",
      services: "General Dentistry",
      onlinePresence: "Google Maps",
      recommendedPackage: "Molar (R4,499)",
      estimatedValue: 4499,
      hasWebsite: false,
      nextAction: "Verify phone, then community approach",
    },
    {
      name: "The Family Dentist",
      sector: "Dental",
      subSector: "Family Dentistry",
      location: "Pretoria East",
      area: "Faerie Glen",
      phone: "Verify via Snupit",
      rating: 4.4,
      tier: 2,
      stage: "new",
      status: "active",
      source: "research",
      notes: "Family branding in premium suburb. Parents book online, check hours, look for child-friendly environments.",
      address: "Faerie Glen, Pretoria East, 0081",
      hours: "Weekdays + possible Saturday",
      services: "Family Dentistry, General, Pediatric",
      onlinePresence: "Snupit listing only",
      recommendedPackage: "Crown (R8,999)",
      estimatedValue: 8999,
      hasWebsite: false,
      nextAction: "Verify phone, demo with Kids Welcome section",
    },
    {
      name: "Pretoria Smile",
      sector: "Dental",
      subSector: "Cosmetic Dentistry",
      location: "Queenswood, Pretoria",
      area: "Queenswood",
      phone: "Verify via Snupit",
      rating: 4.2,
      tier: 2,
      stage: "new",
      status: "active",
      source: "research",
      notes: "Cosmetic/smile focus. Portfolio website almost mandatory. Middle-to-upper income suburb.",
      address: "Queenswood, Pretoria",
      hours: "Standard business hours",
      services: "General Dentistry, Cosmetic Dentistry",
      onlinePresence: "Snupit listing only",
      recommendedPackage: "Crown (R8,999)",
      estimatedValue: 8999,
      hasWebsite: false,
      nextAction: "Verify phone, pitch with before/after gallery",
    },
    {
      name: "Dr Larochelle vd Bergh",
      sector: "Dental",
      subSector: "General Dentistry",
      location: "Queenswood, Pretoria",
      area: "Queenswood",
      phone: "Verify via Queenswood Medical Centre",
      rating: 4.0,
      tier: 2,
      stage: "new",
      status: "active",
      source: "research",
      notes: "New dentist within medical centre. Walk-in referrals from GPs. Needs independent patient base.",
      address: "Queenswood Medical Centre, Queenswood, Pretoria",
      hours: "Medical centre hours (Mon-Fri)",
      services: "General Dentistry",
      onlinePresence: "Snupit (via Queenswood Medical Centre)",
      recommendedPackage: "Molar (R4,499)",
      estimatedValue: 4499,
      hasWebsite: false,
      nextAction: "Verify phone, then call",
    },
    {
      name: "Dentist Consulting Rooms - Eloffsdal",
      sector: "Dental",
      subSector: "General Dentistry",
      location: "Eloffsdal, Pretoria",
      area: "Eloffsdal",
      phone: "Verify via Snupit",
      rating: 4.1,
      tier: 2,
      stage: "new",
      status: "active",
      source: "research",
      notes: "Adjacent to Pretoria North. Legacy practice not yet invested in digital.",
      address: "Eloffsdal, Pretoria",
      hours: "Standard weekday hours",
      services: "General Dentistry",
      onlinePresence: "Snupit directory only",
      recommendedPackage: "Molar (R4,499)",
      estimatedValue: 4499,
      hasWebsite: false,
      nextAction: "Verify phone, outreach call",
    },
    {
      name: "Dr Phalandwa",
      sector: "Dental",
      subSector: "General Dentistry",
      location: "Atteridgeville",
      area: "Atteridgeville",
      phone: "Verify via Snupit",
      rating: 4.3,
      tier: 2,
      stage: "new",
      status: "active",
      source: "research",
      notes: "Atteridgeville-based practice. Community-serving clientele.",
      address: "Atteridgeville / Saulsville",
      hours: "Standard business hours",
      services: "General Dentistry",
      onlinePresence: "Google Maps",
      recommendedPackage: "Molar (R4,499)",
      estimatedValue: 4499,
      hasWebsite: false,
      nextAction: "Verify phone, then call",
    },
    {
      name: "Dr Mahlase",
      sector: "Dental",
      subSector: "General Dentistry",
      location: "Pretoria East",
      area: "Faerie Glen",
      phone: "Verify via Snupit",
      rating: 3.9,
      tier: 3,
      stage: "new",
      status: "active",
      source: "research",
      notes: "Emerging practice in affluent area. Needs affordable entry point.",
      address: "Faerie Glen, Pretoria East",
      hours: "Standard business hours",
      services: "General Dentistry",
      onlinePresence: "Google Maps",
      recommendedPackage: "Molar (R4,499)",
      estimatedValue: 4499,
      hasWebsite: false,
      nextAction: "Verify phone, pitch Molar package",
    },
    {
      name: "Drs Behrens",
      sector: "Dental",
      subSector: "General Dentistry",
      location: "Atteridgeville",
      area: "Atteridgeville",
      phone: "Verify via Snupit",
      rating: 3.5,
      tier: 3,
      stage: "new",
      status: "active",
      source: "research",
      notes: "Lower rating in Atteridgeville. Affordable pitch needed.",
      address: "Atteridgeville / Saulsville",
      hours: "Standard business hours",
      services: "General Dentistry",
      onlinePresence: "Google Maps",
      recommendedPackage: "Molar (R4,499)",
      estimatedValue: 4499,
      hasWebsite: false,
      nextAction: "Phone outreach, affordable pitch",
    },
    {
      name: "Dr Olckers",
      sector: "Dental",
      subSector: "General Dentistry",
      location: "Pretoria North",
      area: "Pretoria North",
      phone: "+27 12 546 0792",
      rating: 4.2,
      tier: 2,
      stage: "new",
      status: "active",
      source: "research",
      notes: "Pretoria North practice with solid 4.2 rating.",
      address: "West Street Medical Centre, 240 Rachel de Beer St, Pta N",
      hours: "Mon-Thu: 8AM-5PM | Fri: 8AM-3PM | Sat: 8AM-1PM",
      services: "General Dentistry",
      onlinePresence: "Google Maps",
      recommendedPackage: "Molar (R4,499)",
      estimatedValue: 4499,
      hasWebsite: false,
      nextAction: "Direct call",
    },
  ];

  // ====== MULTI-SECTOR LEADS FROM FILE 2 ======
  const multiSectorLeads = [
    {
      name: "Matshona Attorneys",
      sector: "Legal",
      subSector: "Law Firm",
      location: "Pretoria CBD",
      area: "Pretoria CBD",
      phone: "+27 72 993 0963",
      rating: 4.9,
      tier: 1,
      stage: "new",
      status: "active",
      source: "research",
      notes: "TOP 5 PRIORITY. 4.9 rating, heart of CBD, Suit 428, 217 Pretorius St. Walk-in with printed mockup/brochure. Candidate for R20k+ corporate site.",
      address: "Suit 428, 217 Pretorius St, Pretoria CBD",
      hours: "Standard business hours",
      services: "Legal Services",
      onlinePresence: "Google Maps",
      recommendedPackage: "Khula (R7,999)",
      estimatedValue: 20000,
      hasWebsite: false,
      hotLead: true,
      nextAction: "Walk-in with printed mockup/brochure",
    },
    {
      name: "TYAN Construction",
      sector: "Construction",
      subSector: "Construction",
      location: "Gauteng",
      area: "Gauteng",
      phone: "+27 11 493 3300",
      rating: 0,
      tier: 1,
      stage: "new",
      status: "active",
      source: "research",
      notes: "TOP 5 PRIORITY. Operating 24 hours, high-ticket projects, needs portfolio for tenders. Direct cold call to director/procurement manager.",
      address: "Gauteng",
      hours: "24 hours",
      services: "Construction Services",
      onlinePresence: "Google Maps",
      recommendedPackage: "Khula (R7,999)",
      estimatedValue: 25000,
      hasWebsite: false,
      hotLead: true,
      nextAction: "Direct cold call to director",
    },
    {
      name: "CLC SA Commercial Logistics",
      sector: "Logistics",
      subSector: "Logistics",
      location: "Gauteng",
      area: "Gauteng",
      phone: "+27 86 122 2252",
      rating: 0,
      tier: 1,
      stage: "new",
      status: "active",
      source: "research",
      notes: "TOP 5 PRIORITY. Missing contact details online, frustrated reviewers, losing business. Cold call to operations manager.",
      address: "Gauteng",
      hours: "Standard business hours",
      services: "Commercial Logistics",
      onlinePresence: "Google Maps",
      recommendedPackage: "Vula (R3,999)",
      estimatedValue: 10000,
      hasWebsite: false,
      hotLead: true,
      nextAction: "Cold call to operations manager",
    },
    {
      name: "The Thinc Clinic",
      sector: "Medical",
      subSector: "Dental Clinic",
      location: "Gauteng",
      area: "Gauteng",
      phone: "+27 11 788 6218",
      rating: 4.9,
      tier: 1,
      stage: "new",
      status: "active",
      source: "research",
      notes: "TOP 5 PRIORITY. 4.9 rating from 335 Google reviews, highly successful practice, no website. Estimated price tag: R30k-R50k.",
      address: "Gauteng",
      hours: "Standard business hours",
      services: "Dental Services",
      onlinePresence: "Google Maps (335 reviews)",
      recommendedPackage: "Implant (R16,999)",
      estimatedValue: 40000,
      hasWebsite: false,
      hotLead: true,
      nextAction: "Cold call receptionist, then tailored email/WhatsApp with Loom video mockup",
    },
    {
      name: "Soweto Funeral Services",
      sector: "Funeral",
      subSector: "Funeral Home",
      location: "Soweto",
      area: "Soweto",
      phone: "+27 82 068 7015",
      rating: 0,
      tier: 1,
      stage: "new",
      status: "active",
      source: "research",
      notes: "TOP 5 PRIORITY. Highly lucrative industry, solid physical presence, zero digital footprint. WhatsApp message with respectful intro and demo link.",
      address: "Soweto",
      hours: "Standard business hours",
      services: "Funeral Services",
      onlinePresence: "Google Maps",
      recommendedPackage: "Vula (R3,999)",
      estimatedValue: 8000,
      hasWebsite: false,
      hotLead: true,
      nextAction: "WhatsApp message with respectful intro and demo link",
    },
    {
      name: "Mfene Attorneys",
      sector: "Legal",
      subSector: "Legal Services",
      location: "Pretoria CBD",
      area: "Pretoria CBD",
      phone: "+27 12 321 2206",
      rating: 0,
      tier: 2,
      stage: "new",
      status: "active",
      source: "research",
      notes: "Pretoria CBD law firm. No website.",
      address: "Pretoria CBD",
      hours: "Standard business hours",
      services: "Legal Services",
      onlinePresence: "Google Maps",
      recommendedPackage: "Vula (R3,999)",
      estimatedValue: 7999,
      hasWebsite: false,
      nextAction: "Cold call",
    },
    {
      name: "SF Sibiya Attorneys",
      sector: "Legal",
      subSector: "Law Firm",
      location: "Pretoria CBD",
      area: "Pretoria CBD",
      phone: "N/A",
      rating: 0,
      tier: 2,
      stage: "new",
      status: "active",
      source: "research",
      notes: "Pretoria CBD law firm. No website. No phone listed - need to research.",
      address: "Pretoria CBD",
      hours: "Standard business hours",
      services: "Legal Services",
      onlinePresence: "Google Maps",
      recommendedPackage: "Vula (R3,999)",
      estimatedValue: 7999,
      hasWebsite: false,
      nextAction: "Research phone number",
    },
    {
      name: "Nthite Attorneys",
      sector: "Legal",
      subSector: "Law Firm",
      location: "Pretoria CBD",
      area: "Pretoria CBD",
      phone: "+27 76 308 3874",
      rating: 0,
      tier: 2,
      stage: "new",
      status: "active",
      source: "research",
      notes: "Pretoria CBD law firm. No website.",
      address: "Pretoria CBD",
      hours: "Standard business hours",
      services: "Legal Services",
      onlinePresence: "Google Maps",
      recommendedPackage: "Vula (R3,999)",
      estimatedValue: 7999,
      hasWebsite: false,
      nextAction: "Cold call",
    },
    {
      name: "The Resting View Guesthouse",
      sector: "Hospitality",
      subSector: "Guesthouse",
      location: "Pretoria East",
      area: "Pretoria East",
      phone: "N/A",
      rating: 0,
      tier: 2,
      stage: "new",
      status: "active",
      source: "research",
      notes: "Pretoria East guesthouse. No website - missing online booking revenue.",
      address: "Pretoria East",
      hours: "24 hours",
      services: "Guesthouse Accommodation",
      onlinePresence: "Google Maps",
      recommendedPackage: "Khula (R7,999)",
      estimatedValue: 7999,
      hasWebsite: false,
      nextAction: "Research phone, then call",
    },
    {
      name: "Camellia Haven",
      sector: "Hospitality",
      subSector: "Guest House",
      location: "Pretoria East",
      area: "Pretoria East",
      phone: "N/A",
      rating: 0,
      tier: 2,
      stage: "new",
      status: "active",
      source: "research",
      notes: "Pretoria East guest house. No website.",
      address: "Pretoria East",
      hours: "24 hours",
      services: "Guesthouse Accommodation",
      onlinePresence: "Google Maps",
      recommendedPackage: "Khula (R7,999)",
      estimatedValue: 7999,
      hasWebsite: false,
      nextAction: "Research phone, then call",
    },
    {
      name: "Mabona Funeral Undertakers",
      sector: "Funeral",
      subSector: "Funeral Home",
      location: "Soweto",
      area: "Soweto",
      phone: "+27 11 936 9000",
      rating: 0,
      tier: 2,
      stage: "new",
      status: "active",
      source: "research",
      notes: "Soweto funeral home. Established presence, no digital footprint.",
      address: "Soweto",
      hours: "Standard business hours",
      services: "Funeral Services",
      onlinePresence: "Google Maps",
      recommendedPackage: "Vula (R3,999)",
      estimatedValue: 5999,
      hasWebsite: false,
      nextAction: "WhatsApp outreach",
    },
    {
      name: "Kwa Ndhlovu And Sons Funerals",
      sector: "Funeral",
      subSector: "Funeral Home",
      location: "Soweto",
      area: "Soweto",
      phone: "+27 82 740 2336",
      rating: 0,
      tier: 2,
      stage: "new",
      status: "active",
      source: "research",
      notes: "Soweto funeral home. Family business, no digital footprint.",
      address: "Soweto",
      hours: "Standard business hours",
      services: "Funeral Services",
      onlinePresence: "Google Maps",
      recommendedPackage: "Vula (R3,999)",
      estimatedValue: 5999,
      hasWebsite: false,
      nextAction: "WhatsApp outreach with respectful tone",
    },
    {
      name: "Awethu Funeral Directors",
      sector: "Funeral",
      subSector: "Funeral Home",
      location: "Soweto",
      area: "Soweto",
      phone: "+27 79 257 6600",
      rating: 0,
      tier: 2,
      stage: "new",
      status: "active",
      source: "research",
      notes: "Soweto funeral directors. No digital footprint.",
      address: "Soweto",
      hours: "Standard business hours",
      services: "Funeral Services",
      onlinePresence: "Google Maps",
      recommendedPackage: "Vula (R3,999)",
      estimatedValue: 5999,
      hasWebsite: false,
      nextAction: "WhatsApp outreach",
    },
    {
      name: "RB & Son Transport Gauteng CC",
      sector: "Logistics",
      subSector: "Transportation",
      location: "Gauteng",
      area: "Gauteng",
      phone: "+27 11 974 5984",
      rating: 0,
      tier: 2,
      stage: "new",
      status: "active",
      source: "research",
      notes: "Gauteng transport company. No website.",
      address: "Gauteng",
      hours: "Standard business hours",
      services: "Transportation",
      onlinePresence: "Google Maps",
      recommendedPackage: "Vula (R3,999)",
      estimatedValue: 5999,
      hasWebsite: false,
      nextAction: "Cold call",
    },
    {
      name: "No Boundaries Logistics",
      sector: "Logistics",
      subSector: "Freight Forward",
      location: "Gauteng",
      area: "Gauteng",
      phone: "+27 67 178 9297",
      rating: 0,
      tier: 2,
      stage: "new",
      status: "active",
      source: "research",
      notes: "Gauteng freight forwarder. No website.",
      address: "Gauteng",
      hours: "Standard business hours",
      services: "Freight Forwarding",
      onlinePresence: "Google Maps",
      recommendedPackage: "Vula (R3,999)",
      estimatedValue: 5999,
      hasWebsite: false,
      nextAction: "Cold call",
    },
    {
      name: "Sanjo Construction",
      sector: "Construction",
      subSector: "Construction",
      location: "Gauteng",
      area: "Gauteng",
      phone: "+27 86 117 2656",
      rating: 0,
      tier: 2,
      stage: "new",
      status: "active",
      source: "research",
      notes: "Gauteng construction firm. Needs portfolio website for tenders.",
      address: "Gauteng",
      hours: "Standard business hours",
      services: "Construction Services",
      onlinePresence: "Google Maps",
      recommendedPackage: "Khula (R7,999)",
      estimatedValue: 15000,
      hasWebsite: false,
      nextAction: "Cold call with portfolio angle",
    },
    {
      name: "Cross Over School",
      sector: "Education",
      subSector: "Private School",
      location: "Gauteng",
      area: "Gauteng",
      phone: "+27 10 534 7495",
      rating: 0,
      tier: 2,
      stage: "new",
      status: "active",
      source: "research",
      notes: "Private school. Needs Presenca or Ikredibo package.",
      address: "Gauteng",
      hours: "Standard school hours",
      services: "Education",
      onlinePresence: "Google Maps",
      recommendedPackage: "Presenca (R4,999)",
      estimatedValue: 9999,
      hasWebsite: false,
      nextAction: "Cold call with school-specific pitch",
    },
    {
      name: "Japari School",
      sector: "Education",
      subSector: "Private School",
      location: "Gauteng",
      area: "Gauteng",
      phone: "+27 11 646 2132",
      rating: 0,
      tier: 2,
      stage: "new",
      status: "active",
      source: "research",
      notes: "Private school. Strong candidate for school package.",
      address: "Gauteng",
      hours: "Standard school hours",
      services: "Education",
      onlinePresence: "Google Maps",
      recommendedPackage: "Ikredibo (R9,999)",
      estimatedValue: 9999,
      hasWebsite: false,
      nextAction: "Cold call with school-specific pitch",
    },
    {
      name: "Brandcliff House Private School",
      sector: "Education",
      subSector: "Private School",
      location: "Gauteng",
      area: "Gauteng",
      phone: "+27 11 476 4174",
      rating: 0,
      tier: 2,
      stage: "new",
      status: "active",
      source: "research",
      notes: "Private school. No website.",
      address: "Gauteng",
      hours: "Standard school hours",
      services: "Education",
      onlinePresence: "Google Maps",
      recommendedPackage: "Presenca (R4,999)",
      estimatedValue: 9999,
      hasWebsite: false,
      nextAction: "Cold call with school-specific pitch",
    },
    {
      name: "Poplar Academy",
      sector: "Education",
      subSector: "Private School",
      location: "Gauteng",
      area: "Gauteng",
      phone: "+27 82 655 0723",
      rating: 0,
      tier: 2,
      stage: "new",
      status: "active",
      source: "research",
      notes: "Private school. No website.",
      address: "Gauteng",
      hours: "Standard school hours",
      services: "Education",
      onlinePresence: "Google Maps",
      recommendedPackage: "Presenca (R4,999)",
      estimatedValue: 9999,
      hasWebsite: false,
      nextAction: "Cold call with school-specific pitch",
    },
    {
      name: "The Medical Centre",
      sector: "Medical",
      subSector: "Medical Center",
      location: "Gauteng",
      area: "Gauteng",
      phone: "+27 11 622 6254",
      rating: 0,
      tier: 2,
      stage: "new",
      status: "active",
      source: "research",
      notes: "Medical centre. No website.",
      address: "Gauteng",
      hours: "Standard business hours",
      services: "Medical Services",
      onlinePresence: "Google Maps",
      recommendedPackage: "Khula (R7,999)",
      estimatedValue: 7999,
      hasWebsite: false,
      nextAction: "Cold call",
    },
    {
      name: "Cosmo City Dental Centre",
      sector: "Dental",
      subSector: "Dental Clinic",
      location: "Gauteng",
      area: "Gauteng",
      phone: "+27 61 524 2458",
      rating: 0,
      tier: 2,
      stage: "new",
      status: "active",
      source: "research",
      notes: "Dental clinic in Cosmo City area. No website.",
      address: "Gauteng",
      hours: "Standard business hours",
      services: "General Dentistry",
      onlinePresence: "Google Maps",
      recommendedPackage: "Molar (R4,499)",
      estimatedValue: 4499,
      hasWebsite: false,
      nextAction: "Cold call",
    },
    {
      name: "Eden Dental Centre",
      sector: "Dental",
      subSector: "Dental Clinic",
      location: "Gauteng",
      area: "Gauteng",
      phone: "+27 11 453 7612",
      rating: 0,
      tier: 2,
      stage: "new",
      status: "active",
      source: "research",
      notes: "Dental clinic. No website.",
      address: "Gauteng",
      hours: "Standard business hours",
      services: "General Dentistry",
      onlinePresence: "Google Maps",
      recommendedPackage: "Molar (R4,499)",
      estimatedValue: 4499,
      hasWebsite: false,
      nextAction: "Cold call",
    },
    {
      name: "PTA East Guest Rooms",
      sector: "Hospitality",
      subSector: "Hospitality",
      location: "Pretoria East",
      area: "Pretoria East",
      phone: "N/A",
      rating: 0,
      tier: 2,
      stage: "new",
      status: "active",
      source: "research",
      notes: "Pretoria East guest rooms. No website.",
      address: "Pretoria East",
      hours: "24 hours",
      services: "Guest Accommodation",
      onlinePresence: "Google Maps",
      recommendedPackage: "Vula (R3,999)",
      estimatedValue: 3999,
      hasWebsite: false,
      nextAction: "Research phone",
    },
    {
      name: "Dr. Cajee (Parkstation)",
      sector: "Medical",
      subSector: "General Practitioner",
      location: "Gauteng",
      area: "Gauteng",
      phone: "+27 11 333 4597",
      rating: 0,
      tier: 2,
      stage: "new",
      status: "active",
      source: "research",
      notes: "General practitioner. No website.",
      address: "Gauteng",
      hours: "Standard business hours",
      services: "General Practice",
      onlinePresence: "Google Maps",
      recommendedPackage: "Vula (R3,999)",
      estimatedValue: 3999,
      hasWebsite: false,
      nextAction: "Cold call",
    },
    {
      name: "Dr H Haffejee",
      sector: "Medical",
      subSector: "General Practitioner",
      location: "Gauteng",
      area: "Gauteng",
      phone: "+27 11 834 1554",
      rating: 0,
      tier: 2,
      stage: "new",
      status: "active",
      source: "research",
      notes: "General practitioner. No website.",
      address: "Gauteng",
      hours: "Standard business hours",
      services: "General Practice",
      onlinePresence: "Google Maps",
      recommendedPackage: "Vula (R3,999)",
      estimatedValue: 3999,
      hasWebsite: false,
      nextAction: "Cold call",
    },
    {
      name: "Dr Marlin J McKay",
      sector: "Medical",
      subSector: "Medical Center",
      location: "Gauteng",
      area: "Gauteng",
      phone: "+27 11 672 2129",
      rating: 0,
      tier: 2,
      stage: "new",
      status: "active",
      source: "research",
      notes: "Medical centre. No website.",
      address: "Gauteng",
      hours: "Standard business hours",
      services: "Medical Services",
      onlinePresence: "Google Maps",
      recommendedPackage: "Khula (R7,999)",
      estimatedValue: 7999,
      hasWebsite: false,
      nextAction: "Cold call",
    },
    {
      name: "Cahi Dental Practice",
      sector: "Dental",
      subSector: "Dentist",
      location: "Gauteng",
      area: "Gauteng",
      phone: "+27 11 305 9300",
      rating: 0,
      tier: 2,
      stage: "new",
      status: "active",
      source: "research",
      notes: "Dental practice. No website.",
      address: "Gauteng",
      hours: "Standard business hours",
      services: "General Dentistry",
      onlinePresence: "Google Maps",
      recommendedPackage: "Molar (R4,499)",
      estimatedValue: 4499,
      hasWebsite: false,
      nextAction: "Cold call",
    },
    {
      name: "Molar Bear Dental",
      sector: "Dental",
      subSector: "Dentist",
      location: "Gauteng",
      area: "Gauteng",
      phone: "+27 11 482 1592",
      rating: 0,
      tier: 2,
      stage: "new",
      status: "active",
      source: "research",
      notes: "Dental practice. No website.",
      address: "Gauteng",
      hours: "Standard business hours",
      services: "General Dentistry",
      onlinePresence: "Google Maps",
      recommendedPackage: "Molar (R4,499)",
      estimatedValue: 4499,
      hasWebsite: false,
      nextAction: "Cold call",
    },
    {
      name: "Ziyaad Dental Surgery",
      sector: "Dental",
      subSector: "Dental Clinic",
      location: "Gauteng",
      area: "Gauteng",
      phone: "+27 11 403 6786",
      rating: 0,
      tier: 2,
      stage: "new",
      status: "active",
      source: "research",
      notes: "Dental surgery. No website.",
      address: "Gauteng",
      hours: "Standard business hours",
      services: "Dental Surgery",
      onlinePresence: "Google Maps",
      recommendedPackage: "Crown (R8,999)",
      estimatedValue: 8999,
      hasWebsite: false,
      nextAction: "Cold call",
    },
  ];

  const allLeads = [...dentalLeads, ...multiSectorLeads];

  console.log(`Seeding ${allLeads.length} leads...`);

  for (const lead of allLeads) {
    await prisma.lead.create({ data: lead });
  }

  // Add sample activities for some leads
  const sampleActivities = [
    { leadName: "Dr. Elaine de Lange Dentist", type: "note", summary: "Identified as highest priority dental lead. 4.9 rating, 562 Facebook likes, no website.", outcome: "Ready for ProtoLead demo build" },
    { leadName: "The Thinc Clinic", type: "note", summary: "335 Google reviews with 4.9 rating. Highly successful practice. Estimated R30k-R50k project.", outcome: "Prepare Loom video mockup" },
    { leadName: "Matshona Attorneys", type: "note", summary: "4.9 rating in heart of Pretoria CBD. Suit 428, 217 Pretorius St.", outcome: "Prepare printed mockup for walk-in" },
    { leadName: "DR MOTHUPI DENTAL STUDIO", type: "note", summary: "Perfect 5.0 rating. Saturday hours. B-BBEE angle strong here.", outcome: "Leverage B-BBEE Level 1 status in pitch" },
    { leadName: "Refresh Dental", type: "note", summary: "Perfect 5-star in affluent Lyttelton Manor. Premium market expectations.", outcome: "Build premium ProtoLead demo" },
  ];

  for (const act of sampleActivities) {
    const lead = await prisma.lead.findFirst({ where: { name: act.leadName } });
    if (lead) {
      await prisma.activity.create({
        data: {
          leadId: lead.id,
          type: act.type,
          summary: act.summary,
          outcome: act.outcome,
        },
      });
    }
  }

  console.log(`Seeded ${allLeads.length} leads and ${sampleActivities.length} activities.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
